services:
  frontend:
    image: echocad_fronted:dev_v1
    build:
      dockerfile: Dockerfile
    container_name: echocad_frontend
    networks:
      - echocad_network
    ports:
      - 80:80
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: dev_morumbi_cloudflared
    restart: unless-stopped
    depends_on:
      - frontend
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN} --url http://frontend:80
    networks:
      - echocad_network

networks:
  echocad_network:
    driver: bridge