services:
  mariadb:
    image: mariadb:11.4
    container_name: echocad_dbms
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-default_password}"
      MYSQL_USER: "${MYSQL_USER:-user}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-echocad_password}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-echocad_db}"
      MYSQL_INITDB_SKIP_TZINFO: "${MYSQL_INITDB_SKIP_TZINFO:-yes}"
    networks:
      - echocad_network
    ports:
      - "${MYSQL_HOST_PORT:-3306}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "${MYSQL_USER:-echocad_admin}", "-p${MYSQL_PASSWORD:-echocad_admin_password}" ]
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
  backend:
    image: echocad_server:dev_v1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echocad_server
    environment:
      database_url: ${DATABASE_URL}
    networks:
      - echocad_network
    ports:
      - 8000:8000
    depends_on:
      - mariadb

volumes:
  mariadb_data:

networks:
  echocad_network:
    driver: bridge
