"""ajusta relacionamentos e adiciona id_user

Revision ID: 10e6345c7312
Revises: bff4dbc79b56
Create Date: 2026-05-03 09:28:08.989401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10e6345c7312'
down_revision: Union[str, Sequence[str], None] = 'bff4dbc79b56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projeto', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projeto', 'usuario', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projeto', type_='foreignkey')
    op.drop_column('projeto', 'id_user')
    # ### end Alembic commands ###
