"""criacao database

Revision ID: 1262510638fc
Revises: 
Create Date: 2026-04-24 21:20:34.982518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1262510638fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Calculos',
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('entrada_json', sa.JSON(), nullable=True),
    sa.Column('resultado_json', sa.JSON(), nullable=True),
    sa.Column('regra_aplicada', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Documentos_gerados',
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=255), nullable=True),
    sa.Column('data_geracao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Elementos',
    sa.Column('layer', sa.String(length=100), nullable=True),
    sa.Column('geometria', sa.String(length=100), nullable=True),
    sa.Column('comprimento', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('area', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('categoria_tecnica_tipo', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('files_cad',
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('upload_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('Coordenadas',
    sa.Column('id_elementos', sa.Integer(), nullable=True),
    sa.Column('x', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('y', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_elementos'], ['Elementos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Especificacoes_tecnicas',
    sa.Column('id_documentos_gerados', sa.Integer(), nullable=True),
    sa.Column('categoria_tecnica', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('materiais_previstos', sa.Text(), nullable=True),
    sa.Column('norma_referencia', sa.String(length=150), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_documentos_gerados'], ['Documentos_gerados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Memoriais_calculo',
    sa.Column('id_documentos_gerados', sa.Integer(), nullable=True),
    sa.Column('id_calculos', sa.Integer(), nullable=True),
    sa.Column('resultados', sa.Text(), nullable=True),
    sa.Column('norma_referencia', sa.String(length=150), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_calculos'], ['Calculos.id'], ),
    sa.ForeignKeyConstraint(['id_documentos_gerados'], ['Documentos_gerados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Projetos',
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('descricao_projeto', sa.Text(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Arquivos',
    sa.Column('caminho', sa.String(length=255), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=150), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('id_projetos', sa.Integer(), nullable=True),
    sa.Column('id_calculos', sa.Integer(), nullable=True),
    sa.Column('id_documentos_gerados', sa.Integer(), nullable=True),
    sa.Column('id_elementos', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_calculos'], ['Calculos.id'], ),
    sa.ForeignKeyConstraint(['id_documentos_gerados'], ['Documentos_gerados.id'], ),
    sa.ForeignKeyConstraint(['id_elementos'], ['Elementos.id'], ),
    sa.ForeignKeyConstraint(['id_projetos'], ['Projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Comandos_ia',
    sa.Column('comando_original', sa.Text(), nullable=True),
    sa.Column('intencao_detectada', sa.String(length=255), nullable=True),
    sa.Column('parametros_extraidos', sa.JSON(), nullable=True),
    sa.Column('data', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_projetos', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_projetos'], ['Projetos.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Processamento',
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('log_erro', sa.Text(), nullable=True),
    sa.Column('versao_parser', sa.String(length=50), nullable=True),
    sa.Column('id_arquivos', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_arquivos'], ['Arquivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('calculos')
    op.drop_table('memoriais_calculo')
    op.drop_table('elementos')
    op.drop_index(op.f('email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('projetos')
    op.drop_table('especificacoes_tecnicas')
    op.drop_table('processamento')
    op.drop_table('comandos_ia')
    op.drop_table('documentos_gerados')
    op.drop_table('coordenadas')
    op.drop_table('arquivos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arquivos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('caminho', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('nome_arquivo', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('iipo', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_projetos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_calculos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_documentos_gerados', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_elementos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_calculos'], ['calculos.id'], name=op.f('arquivos_ibfk_2')),
    sa.ForeignKeyConstraint(['id_documentos_gerados'], ['documentos_gerados.id'], name=op.f('arquivos_ibfk_3')),
    sa.ForeignKeyConstraint(['id_elementos'], ['elementos.id'], name=op.f('arquivos_ibfk_4')),
    sa.ForeignKeyConstraint(['id_projetos'], ['projetos.id'], name=op.f('arquivos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('coordenadas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_elementos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('x', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('y', mysql.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('ordem', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_elementos'], ['elementos.id'], name=op.f('coordenadas_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('documentos_gerados',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo_documento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('caminho_arquivo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data_geracao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('comandos_ia',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('comando_original', mysql.TEXT(), nullable=True),
    sa.Column('intencao_detectada', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('parametros_extraidos', mysql.JSON(), nullable=True),
    sa.Column('data', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_projetos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_projetos'], ['projetos.id'], name=op.f('comandos_ia_ibfk_2')),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('comandos_ia_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('processamento',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_inicio', mysql.DATETIME(), nullable=True),
    sa.Column('data_fim', mysql.DATETIME(), nullable=True),
    sa.Column('log_erro', mysql.TEXT(), nullable=True),
    sa.Column('versao_parser', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('id_arquivos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_arquivos'], ['arquivos.id'], name=op.f('processamento_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('especificacoes_tecnicas',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_documentos_gerados', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria_tecnica', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('materiais_previstos', mysql.TEXT(), nullable=True),
    sa.Column('norma_referencia', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('observacoes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_documentos_gerados'], ['documentos_gerados.id'], name=op.f('especificacoes_tecnicas_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projetos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('data_criacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('descricao_projeto', mysql.TEXT(), nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('projetos_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'usuario', ['email'], unique=True)
    op.create_table('elementos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('layer', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('geometria', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('comprimento', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('area', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('categoria_tecnica_tipo', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('memoriais_calculo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_documentos_gerados', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_calculos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resultados', mysql.TEXT(), nullable=True),
    sa.Column('norma_referencia', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('observacoes', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['id_calculos'], ['calculos.id'], name=op.f('memoriais_calculo_ibfk_2')),
    sa.ForeignKeyConstraint(['id_documentos_gerados'], ['documentos_gerados.id'], name=op.f('memoriais_calculo_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('calculos',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('entrada_json', mysql.JSON(), nullable=True),
    sa.Column('resultado_json', mysql.JSON(), nullable=True),
    sa.Column('regra_aplicada', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Processamento')
    op.drop_table('Comandos_ia')
    op.drop_table('Arquivos')
    op.drop_table('Projetos')
    op.drop_table('Memoriais_calculo')
    op.drop_table('Especificacoes_tecnicas')
    op.drop_table('Coordenadas')
    op.drop_table('files_cad')
    op.drop_table('Usuario')
    op.drop_table('Elementos')
    op.drop_table('Documentos_gerados')
    op.drop_table('Calculos')
    # ### end Alembic commands ###
