"""Corrigir tipo da coluna id de reports

Revision ID: 986c80d0173e
Revises: a6add346fabd
Create Date: 2026-05-09 15:52:33.194498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986c80d0173e'
down_revision: Union[str, Sequence[str], None] = 'a6add346fabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
