"""remove unique constraint from blueprints and reports path

Revision ID: a315325366fd
Revises: 7cdb3e73acf8
Create Date: 2026-05-27 23:02:53.285495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a315325366fd'
down_revision: Union[str, Sequence[str], None] = '7cdb3e73acf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('path'), table_name='blueprints')
    op.drop_index(op.f('path'), table_name='reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('path'), 'reports', ['path'], unique=True)
    op.create_index(op.f('path'), 'blueprints', ['path'], unique=True)
    # ### end Alembic commands ###
