"""inicializaçao do banco de dados.

Revision ID: bff4dbc79b56
Revises: 
Create Date: 2026-05-03 09:15:59.861770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff4dbc79b56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('normas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('especificacao_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memorial_calculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planta_cad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projeto_norma',
    sa.Column('id_norma', sa.Integer(), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_norma'], ['normas.id'], ),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id'], ),
    sa.PrimaryKeyConstraint('id_norma', 'id_projeto')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projeto_norma')
    op.drop_table('planta_cad')
    op.drop_table('memorial_calculo')
    op.drop_table('especificacao_tecnica')
    op.drop_table('usuario')
    op.drop_table('projeto')
    op.drop_table('normas')
    # ### end Alembic commands ###
