"""criacao database

Revision ID: d7ea2dabf542
Revises: 
Create Date: 2026-04-29 15:36:27.896178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7ea2dabf542'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Norma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('conexao', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('files_cad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=False),
    sa.Column('upload_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash')
    )
    op.create_table('Projeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cliente', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Especificacao_tecnica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.Column('id_antigo', sa.Integer(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('melhorias', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_antigo'], ['Especificacao_tecnica.id'], ),
    sa.ForeignKeyConstraint(['id_projeto'], ['Projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Memorial_calculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.Column('id_antigo', sa.Integer(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('melhorias', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_antigo'], ['Memorial_calculo.id'], ),
    sa.ForeignKeyConstraint(['id_projeto'], ['Projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Planta_cad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_projeto'], ['Projeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Projeto_norma',
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.Column('id_norma', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_norma'], ['Norma.id'], ),
    sa.ForeignKeyConstraint(['id_projeto'], ['Projeto.id'], ),
    sa.PrimaryKeyConstraint('id_projeto', 'id_norma')
    )
    op.create_table('Projeto_planta',
    sa.Column('id_projeto', sa.Integer(), nullable=False),
    sa.Column('id_planta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_planta'], ['Planta_cad.id'], ),
    sa.ForeignKeyConstraint(['id_projeto'], ['Projeto.id'], ),
    sa.PrimaryKeyConstraint('id_projeto', 'id_planta')
    )
    op.drop_table('memorial_calculo')
    op.drop_table('norma')
    op.drop_index(op.f('email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('projeto_planta')
    op.drop_table('planta_cad')
    op.drop_table('projeto')
    op.drop_table('projeto_norma')
    op.drop_table('especificacao_tecnica')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especificacao_tecnica',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('arquivo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('melhorias', mysql.TEXT(), nullable=True),
    sa.Column('versao', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_antigo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_antigo'], ['especificacao_tecnica.id'], name=op.f('especificacao_tecnica_ibfk_2')),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id'], name=op.f('especificacao_tecnica_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projeto_norma',
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_norma', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_norma'], ['norma.id'], name=op.f('projeto_norma_ibfk_2')),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id'], name=op.f('projeto_norma_ibfk_1')),
    sa.PrimaryKeyConstraint('id_projeto', 'id_norma'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projeto',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('descricao', mysql.TEXT(), nullable=True),
    sa.Column('cliente', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('data_criacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name=op.f('projeto_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('planta_cad',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('arquivo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id'], name=op.f('planta_cad_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('projeto_planta',
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_planta', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_planta'], ['planta_cad.id'], name=op.f('projeto_planta_ibfk_2')),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id'], name=op.f('projeto_planta_ibfk_1')),
    sa.PrimaryKeyConstraint('id_projeto', 'id_planta'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('usuario',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('senha', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cargo', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('email'), 'usuario', ['email'], unique=True)
    op.create_table('norma',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('conexao', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('data_criacao', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('memorial_calculo',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('arquivo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('melhorias', mysql.TEXT(), nullable=True),
    sa.Column('versao', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('id_projeto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_antigo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_antigo'], ['memorial_calculo.id'], name=op.f('memorial_calculo_ibfk_2')),
    sa.ForeignKeyConstraint(['id_projeto'], ['projeto.id'], name=op.f('memorial_calculo_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('Projeto_planta')
    op.drop_table('Projeto_norma')
    op.drop_table('Planta_cad')
    op.drop_table('Memorial_calculo')
    op.drop_table('Especificacao_tecnica')
    op.drop_table('Projeto')
    op.drop_table('files_cad')
    op.drop_table('Usuario')
    op.drop_table('Norma')
    # ### end Alembic commands ###
